Make the bash add-parents fail if an invalid SHA1 is given as a parent.
We only check for the length (40 chars), but that's enough to reject
the new keywords add-parents.py will have.

diff --git a/bin/add-parents b/bin/add-parents
--- a/bin/add-parents
+++ b/bin/add-parents
@@ -43,6 +43,10 @@ else
 fi'
 code="$codebefore"
 while read newparent child x; do
+    if [[ ${#newparent} -ne 40 ]]; then
+        echo "error: invalid commit ID: '${newparent}'" >&2
+        exit 1
+    fi
     code="$code    $child) merge_gitrev=$newparent;;
 "
 done < "$parentmap"
